Repository MoneyMakersClub/mmc-frontend, pull requests merged in 2024-11, with the labels that each got.

#76 Design/#53 | 메인페이지 관련 페이지들 퍼블리싱
  bookduck/package.json
  bookduck/src/App.jsx
  bookduck/src/assets/common/alarm.svg
  bookduck/src/assets/common/book-cover.png
  bookduck/src/assets/common/book-cover.svg
  bookduck/src/assets/common/logo-text.svg
  bookduck/src/assets/common/main-duck.svg
  bookduck/src/assets/common/people.svg
  bookduck/src/assets/common/right-yellow.svg
  bookduck/src/assets/common/setting.svg
  bookduck/src/assets/common/trash.svg
  bookduck/src/assets/mainPage/bookcard.svg
  bookduck/src/assets/mainPage/delete.svg
  bookduck/src/assets/mainPage/go-edit.svg
  bookduck/src/assets/mainPage/help-circle.svg
  bookduck/src/assets/mainPage/info-memobox.svg
  bookduck/src/assets/mainPage/info-musicbox.svg
  bookduck/src/assets/mainPage/menu-vertical.svg
  bookduck/src/assets/mainPage/music.svg
  bookduck/src/assets/mainPage/plus.svg
  bookduck/src/components/MainPage/DraggableList.jsx
  bookduck/src/components/MainPage/ExtractCard.jsx
  bookduck/src/components/MainPage/OneBookCard.jsx
  bookduck/src/components/MainPage/ReadingSpaceComponent.jsx
  bookduck/src/components/MainPage/ReviewCard.jsx
  bookduck/src/components/RecordingPage/DirectRegister.jsx
  bookduck/src/components/SearchPage/CarouselComponent.jsx
  bookduck/src/components/SearchPage/SearchArchiveComponent.jsx
  bookduck/src/components/SearchPage/SearchBookComponent.jsx
  bookduck/src/components/SearchPage/SearchUserComponent.jsx
  bookduck/src/components/common/BookListView.jsx
  bookduck/src/components/common/BookListViewDropdown.jsx
  bookduck/src/components/common/BottomNavbar.jsx
  bookduck/src/components/common/BottomSheetModal.jsx
  bookduck/src/components/common/Header2.jsx
  bookduck/src/components/common/ListBottomSheet.jsx
  bookduck/src/components/common/SearchComponent.jsx
  bookduck/src/pages/MainPage/MainPage.jsx
  bookduck/src/pages/MainPage/SelectCardPage.jsx
  bookduck/src/pages/MainPage/SelectCustomPage.jsx
  bookduck/src/pages/MainPage/SelectExtractPage.jsx
  bookduck/src/pages/MainPage/SelectReviewPage.jsx
  bookduck/src/pages/SearchPage/SearchMainPage.jsx
  bookduck/src/pages/SearchPage/SearchRegisterPage.jsx
  bookduck/src/pages/SettingPage/SettingPage.jsx
  bookduck/tailwind.config.js
  bookduck/yarn.lock
Labels: UI 💄

#72 Design/#57 | 서재 메인페이지
  bookduck/index.html
  bookduck/package.json
  bookduck/src/App.jsx
  bookduck/src/assets/libraryPage/cover-icon.svg
  bookduck/src/assets/libraryPage/cover-img-ex.svg
  bookduck/src/assets/libraryPage/list-icon.svg
  bookduck/src/components/LibraryPage/BookCasePage.jsx
  bookduck/src/components/LibraryPage/BookListPage.jsx
  bookduck/src/components/LibraryPage/CoverIcon.jsx
  bookduck/src/components/LibraryPage/ListIcon.jsx
  bookduck/src/components/RecordingPage/Cards.jsx
  bookduck/src/components/RecordingPage/ColorPalette.jsx
  bookduck/src/components/RecordingPage/ColoredAuthorComponent.jsx
  bookduck/src/components/RecordingPage/ExtractView.jsx
  bookduck/src/components/RecordingPage/ReviewComponents.jsx
  bookduck/src/components/RecordingPage/ReviewWritingComponent.jsx
  bookduck/src/components/RecordingPage/TotalView.jsx
  bookduck/src/components/SearchPage/BookComponent.jsx
  bookduck/src/components/common/BottomSheetMenuComponent.jsx
  bookduck/src/components/common/RoundedTabComponent.jsx
  bookduck/src/constant/colorDefaultPalette.js
  bookduck/src/constant/colorThemePalette.js
  bookduck/src/pages/LibraryPage/LibraryPage.jsx
  bookduck/src/pages/RecordingPage/ArchivePage.jsx
  bookduck/src/pages/RecordingPage/CardDecorationPage.jsx
  bookduck/src/pages/RecordingPage/RecordingPage.jsx
  bookduck/src/pages/SearchPage/SearchBookPage.jsx
  bookduck/src/router/router.js
  bookduck/src/store/useReviewColorStore.js
  bookduck/tailwind.config.js
  bookduck/yarn.lock
Labels: UI 💄

#71 Design/#56 | 감상평 카드 꾸미기 퍼블리싱
  bookduck/src/components/common/RoundedTabComponent.jsx
Labels: UI 💄

#65 Design/#51 | 책 정보 페이지(기본, 직접등록)
  bookduck/src/App.jsx
  bookduck/src/api/api.js
  bookduck/src/assets/bookinfoPage/left-quotmark.svg
  bookduck/src/assets/bookinfoPage/menu-vertical.svg
  bookduck/src/assets/bookinfoPage/right-quotmark.svg
  bookduck/src/assets/bookinfoPage/start-yes.svg
  bookduck/src/components/BookInfoPage/BookInfo.jsx
  bookduck/src/components/BookInfoPage/BookPlot.jsx
  bookduck/src/components/BookInfoPage/MyComment.jsx
  bookduck/src/components/CharacterPage/UserDuck.jsx
  bookduck/src/pages/BookInfoPage/BookInfoPage.jsx
  bookduck/src/pages/BookInfoPage/BoonInfoAddedPage.jsx
  bookduck/tailwind.config.js
Labels: UI 💄

#68 Design/#61 | 통계 페이지
  bookduck/src/App.jsx
  bookduck/src/api/api.js
  bookduck/src/assets/bookinfoPage/star-yes.svg
  bookduck/src/assets/statisticsPage/rectangle1.svg
  bookduck/src/assets/statisticsPage/rectangle2.svg
  bookduck/src/assets/statisticsPage/rectangle3.svg
  bookduck/src/assets/statisticsPage/rectangle4.svg
  bookduck/src/assets/statisticsPage/rectangle5.svg
  bookduck/src/assets/statisticsPage/right.svg
  bookduck/src/assets/statisticsPage/star.svg
  bookduck/src/components/BookInfoPage/MyComment.jsx
  bookduck/src/components/StatisticsPage/BookRecord.jsx
  bookduck/src/components/StatisticsPage/MonthlyReading.jsx
  bookduck/src/components/StatisticsPage/MyKeyword.jsx
  bookduck/src/components/StatisticsPage/PreferredAuthor.jsx
  bookduck/src/components/StatisticsPage/PreferredGenre.jsx
  bookduck/src/components/StatisticsPage/RecordCalender.jsx
  bookduck/src/components/StatisticsPage/StatisticsHeader.jsx
  bookduck/src/components/StatisticsPage/SummaryFloatingButton.jsx
  bookduck/src/components/StatisticsPage/UserCard.jsx
  bookduck/src/pages/CharacterPage/CharacterCustomPage.jsx
  bookduck/src/pages/StatisticsPage/StatisticsPage.jsx
  bookduck/tailwind.config.js
Labels: UI 💄

#93 Feat/#82 | 서재 관련 API 1차 연결
  bookduck/package.json
  bookduck/src/api/archive.js
  bookduck/src/api/library.js
  bookduck/src/api/reactQuery/queryClient.js
  bookduck/src/api/recording.js
  bookduck/src/assets/common/spinner.svg
  bookduck/src/components/LibraryPage/BookCasePage.jsx
  bookduck/src/components/LibraryPage/BookListPage.jsx
  bookduck/src/components/RecordingPage/Archiving.jsx
  bookduck/src/components/RecordingPage/Library.jsx
  bookduck/src/components/SearchPage/BookComponent.jsx
  bookduck/src/components/common/BookListView.jsx
  bookduck/src/components/common/BottomSheetModal.jsx
  bookduck/src/components/common/ListBottomSheet.jsx
  bookduck/src/components/common/SuspenseLoading.jsx
  bookduck/src/main.jsx
  bookduck/src/pages/LibraryPage/LibraryPage.jsx
  bookduck/yarn.lock
Labels: Feature ✨

#99 Feature/#88 | 통계, 책정보 관련 api 연결
  bookduck/public/assets/items/hairband.glb
  bookduck/public/assets/items/safetyhat.glb
  bookduck/public/assets/items/spanner.glb
  bookduck/src/App.jsx
  bookduck/src/api/bookinfo.js
  bookduck/src/api/character.js
  bookduck/src/api/statistics.js
  bookduck/src/assets/bookinfoPage/heart-no.svg
  bookduck/src/assets/bookinfoPage/heart-yes.svg
  bookduck/src/assets/bookinfoPage/star-half.svg
  bookduck/src/assets/bookinfoPage/star-small-half.svg
  bookduck/src/assets/bookinfoPage/star-small-yes.svg
  bookduck/src/assets/characterPage/bookduck.svg
  bookduck/src/assets/statisticsPage/rectangle1.svg
  bookduck/src/assets/statisticsPage/rectangle2.svg
  bookduck/src/assets/statisticsPage/rectangle3.svg
  bookduck/src/assets/statisticsPage/rectangle4.svg
  bookduck/src/assets/statisticsPage/rectangle5.svg
  bookduck/src/assets/statisticsPage/rectangle6.svg
  bookduck/src/assets/statisticsPage/rectangle7.svg
  bookduck/src/assets/statisticsPage/rectangle8.svg
  bookduck/src/components/BookInfoPage/BookInfo.jsx
  bookduck/src/components/BookInfoPage/BookPlot.jsx
  bookduck/src/components/BookInfoPage/BottomSheetModal2.jsx
  bookduck/src/components/BookInfoPage/InfoView.jsx
  bookduck/src/components/BookInfoPage/MyComment.jsx
  bookduck/src/components/BookInfoPage/UserComment.jsx
  bookduck/src/components/CharacterPage/LevelModal.jsx
  bookduck/src/components/CharacterPage/UserDuck.jsx
  bookduck/src/components/StatisticsPage/ExportCharacter.jsx
  bookduck/src/components/StatisticsPage/MonthlyReading.jsx
  bookduck/src/components/StatisticsPage/MyKeyword.jsx
  bookduck/src/components/StatisticsPage/PreferredAuthor.jsx
  bookduck/src/components/StatisticsPage/PreferredGenre.jsx
  bookduck/src/components/StatisticsPage/UserCard.jsx
  bookduck/src/components/common/Divider2.jsx
  bookduck/src/pages/BookInfoPage/BookInfoPage.jsx
  bookduck/src/pages/BookInfoPage/UserCommentPage.jsx
  bookduck/src/pages/CharacterPage/CharacterPage.jsx
  bookduck/src/pages/StatisticsPage/CharacterExportPage.jsx
  bookduck/src/pages/StatisticsPage/StatisticsPage.jsx
  bookduck/tailwind.config.js
Labels: UI 💄, Feature ✨

#108 ✨ Feat : 폴더 API 연결
  bookduck/src/api/library.js
  bookduck/src/components/LibraryPage/BookCaseComponent.jsx
  bookduck/src/components/LibraryPage/BookCasePage.jsx
  bookduck/src/components/LibraryPage/BookListPage.jsx
  bookduck/src/components/SearchPage/BookComponent.jsx
  bookduck/src/components/common/EditBookListView.jsx
  bookduck/src/pages/LibraryPage/EnterBookCasePage.jsx
  bookduck/src/pages/LibraryPage/LibraryPage.jsx
Labels: Feature ✨

#112 💄 UI: 레벨업/배지 알림 모달창 퍼블리싱
  bookduck/src/components/CharacterPage/CharacterAlarmModal.jsx
Labels: UI 💄

#123 Feat/#94 | 서재 폴더 api 연결
  bookduck/src/api/archive.js
  bookduck/src/api/library.js
  bookduck/src/assets/recordingPage/toggle-off.svg
  bookduck/src/assets/recordingPage/toggle-on.svg
  bookduck/src/components/LibraryPage/BookListPage.jsx
  bookduck/src/components/RecordingPage/ColoredAuthorComponent.jsx
  bookduck/src/components/RecordingPage/DirectRegister.jsx
  bookduck/src/components/RecordingPage/ExtractComponents.jsx
  bookduck/src/components/RecordingPage/ExtractWritingComponent.jsx
  bookduck/src/components/RecordingPage/PublicRange.jsx
  bookduck/src/components/RecordingPage/ReviewComponents.jsx
  bookduck/src/components/RecordingPage/ReviewWritingComponent.jsx
  bookduck/src/components/common/BookListView.jsx
  bookduck/src/pages/LibraryPage/EnterBookCasePage.jsx
  bookduck/src/pages/RecordingPage/ArchiveDetailPage.jsx
  bookduck/src/pages/RecordingPage/CardDecorationPage.jsx
  bookduck/src/pages/RecordingPage/RecordingPage.jsx
Labels: Feature ✨
